SEMANTIC_CONTAINS_RULES: dict[str, dict[str, set[str]]] = {
    "skills": {
        "technical": {
            "python",
            "fastapi",
            "machine learning",
            "java",
            "spring boot",
            "sql",
            "data science",
            "nlp",
            "react",
            "node.js",
            "ui design",
            "android development",
        },
        "tech": {
            "python",
            "fastapi",
            "machine learning",
            "java",
            "spring boot",
            "sql",
            "data science",
            "nlp",
            "react",
            "node.js",
            "ui design",
            "android development",
        },
        "software": {
            "python",
            "fastapi",
            "java",
            "spring boot",
            "react",
            "node.js",
            "android development",
            "sql",
        },
        "developer": {
            "python",
            "fastapi",
            "java",
            "spring boot",
            "react",
            "node.js",
            "android development",
            "sql",
        },
        "programming": {
            "python",
            "java",
            "react",
            "node.js",
            "android development",
            "sql",
            "fastapi",
        },
        "ai": {"machine learning", "data science", "nlp"},
        "ml": {"machine learning"},
        "frontend": {"react", "ui design"},
        "backend": {"python", "fastapi", "java", "spring boot", "node.js", "sql"},
        "mobile": {"android development"},
        "soft skills": {"communication", "teamwork", "leadership"},
        "softskill": {"communication", "teamwork", "leadership"},
        "communication": {"communication"},
        "teamwork": {"teamwork"},
        "leadership": {"leadership"},
    },
    "activities": {
        "hackathon": {"hackathon"},
        "research": {"research"},
        "startup": {"startup cell"},
        "club": {"coding club", "design club"},
        "coding": {"coding club", "hackathon", "cp"},
        "competitive programming": {"cp"},
        "cp": {"cp"},
        "extracurricular": {
            "hackathon",
            "coding club",
            "debate",
            "volunteer",
            "research",
            "design club",
            "startup cell",
            "cp",
        },
    },
    "projects": {
        "technical": {
            "ai research assistant",
            "campus helpdesk bot",
            "attendance tracker",
            "library manager",
            "resume screener",
            "student recommendation engine",
            "portfolio builder",
            "event platform",
            "competitive programming tracker",
        },
        "ai": {
            "ai research assistant",
            "resume screener",
            "student recommendation engine",
        },
        "software": {
            "attendance tracker",
            "library manager",
            "portfolio builder",
            "event platform",
            "competitive programming tracker",
            "Python"
        },
        "competitive programming": {"competitive programming tracker"},
    },
}
